using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScreenServerWPF.Figuras
{
    public class Colores
    {
        #region colores
        static string[] colores = new string[100] {
            "#FFFFFF",
            "#F0FFFF",
            "#F5FFFA",
            "#FFFAFA",
            "#FFFFF0",
            "#F8F8FF",
            "#FFFAF0",
            "#F0F8FF",
            "#E0FFFF",
            "#F0FFF0",
            "#FFFFE0",
            "#FFF5EE",
            "#FFF0F5",
            "#F5F5F5",
            "#FDF5E6",
            "#FFF8DC",
            "#FAF0E6",
            "#FAFAD2",
            "#FFFACD",
            "#F5F5DC",
            "#E6E6FA",
            "#FFEFD5",
            "#FFE4E1",
            "#FAEBD7",
            "#FFEBCD",
            "#FFE4C4",
            "#AFEEEE",
            "#FFE4B5",
            "#DCDCDC",
            "#FFDAB9",
            "#FFDEAD",
            "#EEE8AA",
            "#F5DEB3",
            "#B0E0E6",
            "#7FFFD4",
            "#D3D3D3",
            "#FFC0CB",
            "#ADD8E6",
            "#D8BFD8",
            "#FFB6C1",
            "#87CEFA",
            "#98FB98",
            "#B0C4DE",
            "#F0D58C",
            "#87CEEB",
            "#00FFFF",
            "#00FFFF",
            "#C0C0C0",
            "#DDA0DD",
            "#BEBEBE",
            "#90EE90",
            "#EE82EE",
            "#FFFF00",
            "#40E0D0",
            "#DEB887",
            "#ADFF2F",
            "#D2B48C",
            "#48D1CC",
            "#FFA07A",
            "#66CDAA",
            "#A9A9A9",
            "#DA70D6",
            "#8FBC8F",
            "#00BFFF",
            "#F4A460",
            "#FFD700",
            "#00FA9A",
            "#BDB76B",
            "#6495ED",
            "#FF69B4",
            "#E9967A",
            "#00CED1",
            "#00FF7F",
            "#F08080",
            "#BC8F8F",
            "#FA8072",
            "#7FFF00",
            "#9370DB",
            "#7CFC00",
            "#1E90FF",
            "#9ACD32",
            "#DB7093",
            "#7B68EE",
            "#BA55D3",
            "#FF7F50",
            "#5F9EA0",
            "#20B2AA",
            "#DAA520",
            "#FFA500",
            "#778899",
            "#FF00FF",
            "#FF00FF",
            "#3CB371",
            "#CD853F",
            "#4682B4",
            "#4169E1",
            "#708090",
            "#FF6347",
            "#FF8C00",
            "#6A5ACD"
             };
        #endregion
        public static string NuevoColor()
        {
            Random rdn = new Random();
            return colores[rdn.Next(100)];
        }
    }
}
